#!/usr/bin/env bash
# embed_ecdsa_key.sh
# Embeds the ECDSA public key into the VisionLinkHue source at build time.
#
# Usage: Passed the following environment variables:
#   ECDSA_DEFAULT_PUBLIC_KEY - Base64-encoded public key (required in release builds)
#   BUILT_PRODUCTS_DIR       - Xcode/Xcode-derived data directory (set by build system)
#   SOURCE_FILE              - Path to the Swift file containing the key placeholder
#
# The script reads the base64-encoded key, XOR-obfuscates it with a simple
# byte pattern, and writes a Swift file with the obfuscated byte array.
# This prevents casual extraction of the key from the compiled binary.

set -euo pipefail

# The obfuscation key used to XOR the public key bytes.
# This is NOT cryptographic security — it prevents casual hex-dump extraction.
OBFS_KEY=0xA7

# Skip key embedding in DEBUG builds to avoid test failures.
# In DEBUG mode, the Swift source uses #if DEBUG to override to nil.
# This allows tests to run without requiring ECDSA_DEFAULT_PUBLIC_KEY.
if [ "${CONFIGURATION:-}" = "Debug" ] || [ "${ENABLE_DEBUG_EMBED:-0}" = "0" ] && [ -z "${ECDSA_DEFAULT_PUBLIC_KEY:-}" ]; then
    echo "INFO: DEBUG build or no key configured. Skipping ECDSA key embedding."
    echo "// Auto-generated by embed_ecdsa_key.sh - debug build, no key embedded" > "${SOURCE_FILE}"
    echo "" >> "${SOURCE_FILE}"
    echo "import Foundation" >> "${SOURCE_FILE}"
    echo "" >> "${SOURCE_FILE}"
    echo "/// Obfuscated ECDSA public key bytes embedded at build time." >> "${SOURCE_FILE}"
    echo "/// Generated by the embed_ecdsa_key.sh build-phase script." >> "${SOURCE_FILE}"
    echo "/// In DEBUG builds, this is overridden to nil via #if DEBUG." >> "${SOURCE_FILE}"
    echo "@_exported import VisionLinkHue" >> "${SOURCE_FILE}"
    echo "" >> "${SOURCE_FILE}"
    echo "#if DEBUG" >> "${SOURCE_FILE}"
    echo "internal let _embeddedPublicKeyBytes: Data? = nil" >> "${SOURCE_FILE}"
    echo "#else" >> "${SOURCE_FILE}"
    echo "internal let _embeddedPublicKeyBytes: Data? = nil" >> "${SOURCE_FILE}"
    echo "#endif" >> "${SOURCE_FILE}"
    exit 0
fi

# Read the base64-encoded public key from the environment.
KEY_B64="${ECDSA_DEFAULT_PUBLIC_KEY:-}"

if [ -z "$KEY_B64" ]; then
    echo "WARNING: ECDSA_DEFAULT_PUBLIC_KEY not set in release build. Generating placeholder with nil key."
    echo "// Auto-generated by embed_ecdsa_key.sh - no key configured" > "${SOURCE_FILE}"
    echo "" >> "${SOURCE_FILE}"
    echo "import Foundation" >> "${SOURCE_FILE}"
    echo "" >> "${SOURCE_FILE}"
    echo "/// Obfuscated ECDSA public key bytes embedded at build time." >> "${SOURCE_FILE}"
    echo "/// Generated by the embed_ecdsa_key.sh build-phase script." >> "${SOURCE_FILE}"
    echo "/// In DEBUG builds, this is overridden to nil via #if DEBUG." >> "${SOURCE_FILE}"
    echo "@_exported import VisionLinkHue" >> "${SOURCE_FILE}"
    echo "" >> "${SOURCE_FILE}"
    echo "#if DEBUG" >> "${SOURCE_FILE}"
    echo "internal let _embeddedPublicKeyBytes: Data? = nil" >> "${SOURCE_FILE}"
    echo "#else" >> "${SOURCE_FILE}"
    echo "internal let _embeddedPublicKeyBytes: Data? = nil" >> "${SOURCE_FILE}"
    echo "#endif" >> "${SOURCE_FILE}"
    exit 0
fi

# Decode the base64 key to raw bytes.
KEY_BYTES=$(echo "$KEY_B64" | base64 -d | xxd -p | tr -d '\n')

# Generate the obfuscated byte array.
OBFUSCATED=""
idx=0
while [ $idx -lt ${#KEY_BYTES} ]; do
    # Read 2 hex chars (1 byte).
    HEX="${KEY_BYTES:$idx:2}"
    BYTE=$((16#$HEX))
    # XOR with obfuscation key.
    OBF_BYTE=$(( BYTE ^ OBFS_KEY ))
    # Format as 0xNN.
    OBFUSCATED+=$(printf "0x%02x" $OBF_BYTE)
    if [ $(( idx + 2 )) -lt ${#KEY_BYTES} ]; then
        OBFUSCATED+=", "
    fi
    idx=$(( idx + 2 ))
done

# Write the Swift source file.
cat > "${SOURCE_FILE}" << SWIFTEOF
// Auto-generated by embed_ecdsa_key.sh — do not edit manually.
// This file is regenerated every build from ECDSA_DEFAULT_PUBLIC_KEY.

import Foundation

/// Obfuscated ECDSA P-256 public key bytes embedded at build time.
/// The raw key bytes are XOR-obfuscated with 0xA7 to prevent casual
/// extraction from the compiled binary.
///
/// To regenerate: set ECDSA_DEFAULT_PUBLIC_KEY and rebuild.
internal let _embeddedPublicKeyBytes: Data? = {
    let rawBytes: [UInt8] = [${OBFUSCATED}]
    // De-obfuscate by XORing with the same key.
    return Data(rawBytes.map { UInt8(bitPattern: $0 ^ 0xA7) })
}()
SWIFTEOF

echo "ECDSA public key embedded into ${SOURCE_FILE} ($(echo "$KEY_B64" | base64 -d | wc -c) bytes, obfuscated)"
